# Generated by Django 6.0.2 on 2026-04-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="General", max_length=100),
        ),
    ]
